name: Reusable Workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
              
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

               